// src/data/furnitureData.js

const furnitureItems = [
  {
    id: 1,
    name: "Aesthetic Wooden Chairs",
    description: "Beautifully crafted wooden chairs with a touch of elegance.",
    price: 40000,
    image: "../../public/img/f1.jpg",
  },
  {
    id: 2,
    name: "Foam Seat",
    description: "Comfortable foam seat perfect for any living space.",
    price: 34000,
    image: "../../public/img/f2.jpg",
  },
  {
    id: 3,
    name: "Wooden Chair Colorful",
    description: "Vibrant and colorful wooden chair to brighten up your room.",
    price: 25000,
    image: "../../public/img/f3.jpg",
  },
  {
    id: 4,
    name: "Foam Sofa",
    description: "Luxurious foam sofa for ultimate relaxation.",
    price: 50000,
    image: "../../public/img/f4.jpg",
  },
  {
    id: 5,
    name: "Classic Wooden Chair",
    description: "Timeless wooden chair with a classic design.",
    price: 20000,
    image: "../../public/img/f5.jpg",
  },
  {
    id: 6,
    name: "Modern Lounge Chair",
    description: "Stylish lounge chair with a modern design.",
    price: 30000,
    image: "../../public/img/f6.jpg",
  },
  {
    id: 7,
    name: "Elegant Dining Table",
    description: "Elegant dining table perfect for family meals.",
    price: 60000,
    image: "../../public/img/f7.jpg",
  },
  {
    id: 8,
    name: "Rustic Coffee Table",
    description: "Charming rustic coffee table for a cozy living room.",
    price: 35000,
    image: "../../public/img/f8.jpg",
  },
  {
    id: 9,
    name: "Comfy Recliner",
    description: "Relaxing recliner chair for the ultimate comfort.",
    price: 45000,
    image: "../../public/img/f9.jpg",
  },
  {
    id: 10,
    name: "Minimalist Bookshelf",
    description: "Sleek and minimalist bookshelf to organize your books.",
    price: 20000,
    image: "../../public/img/f10.jpg",
  },
  {
    id: 11,
    name: "Vintage Armchair",
    description: "Elegant vintage armchair with a retro touch.",
    price: 28000,
    image: "../../public/img/f11.jpg",
  },
  {
    id: 12,
    name: "Luxury Bed Frame",
    description: "Luxurious bed frame for a stylish bedroom.",
    price: 70000,
    image: "../../public/img/f12.jpg",
  },
  {
    id: 13,
    name: "Compact Study Desk",
    description: "Space-saving study desk for productivity.",
    price: 15000,
    image: "../../public/img/f13.jpg",
  },
  {
    id: 14,
    name: "Outdoor Patio Set",
    description: "Durable outdoor patio set for your garden.",
    price: 55000,
    image: "../../public/img/f14.jpg",
  },
  {
    id: 15,
    name: "Swivel Office Chair",
    description: "Ergonomic swivel office chair for comfort.",
    price: 32000,
    image: "../../public/img/f15.jpg",
  },
  {
    id: 16,
    name: "Kids Play Table",
    description: "Fun and colorful play table for kids.",
    price: 18000,
    image: "../../public/img/f16.jpg",
  },
  {
    id: 17,
    name: "Elegant Wardrobe",
    description: "Spacious and elegant wardrobe for your clothes.",
    price: 50000,
    image: "../../public/img/f17.jpg",
  },
  {
    id: 18,
    name: "Classic Rocking Chair",
    description: "Comfortable classic rocking chair for relaxation.",
    price: 24000,
    image: "../../public/img/f18.jpg",
  },
  {
    id: 19,
    name: "Modern TV Stand",
    description: "Sleek modern TV stand with storage.",
    price: 38000,
    image: "../../public/img/f19.jpg",
  },
  {
    id: 20,
    name: "Luxurious Sofa Set",
    description: "Luxurious sofa set for a stylish living room.",
    price: 80000,
    image: "../../public/img/f20.jpg",
  },
];

export default furnitureItems;
